# 交易配置
trading:
  # 交易限制
  max_position_ratio: 30  # 单个股票最大持仓比例(0-100)
  max_trade_amount: 500000.00  # 单笔最大交易金额
  min_trade_amount: 1000.00  # 单笔最小交易金额
  min_volume: 100  # 最小交易数量
  volume_step: 100  # 交易数量步长
  price_deviation: 0.02  # 允许的价格偏离度
  trade_frequency_limit: 10  # 每分钟最大交易次数
  
  # 交易时间
  trading_hours:
    start: "09:30:00"  # 交易开始时间
    end: "15:00:00"  # 交易结束时间
  trading_days: [1, 2, 3, 4, 5]  # 交易日（1-5，1表示周一）
  
  # 交易费用
  fees:
    stamp_duty: 0.001  # 印花税（卖出时收取）
    commission: 0.0003  # 交易佣金
    min_commission: 5.00  # 最低佣金
    transfer_fee: 0.00002  # 过户费（沪市收取）
    
  # 订单设置
  order:
    timeout: 120  # 订单超时时间（秒）
    auto_cancel: true  # 超时自动撤单
    price_types: ["limit", "market"]  # 支持的价格类型
    retry_times: 3  # 失败重试次数
    retry_interval: 5  # 重试间隔（秒）

# API配置
api:
  host: "127.0.0.1"
  port: 5000
  version: "v1"
  base_url: "http://127.0.0.1:5000/api/v1"
  backup_urls:
    - "http://localhost:5000/api/v1"
    - "http://127.0.0.1:8000/api/v1"
  health_path: "/health"  # 健康检查接口
  positions_path: "/positions"  # 持仓查询路径
  account_funds_path: "/account/funds"  # 账户资金查询路径
  timeout: 10  # 请求超时时间（秒）
  retry_times: 3  # API重试次数
  retry_interval: 5  # 重试间隔（秒）

# 数据存储配置
data:
  # 文件存储
  dir: "data"  # 数据根目录
  file_encoding: "utf-8"  # 文件编码
  json_indent: 2  # JSON缩进
  
  # 数据文件
  files:
    positions: "positions.json"  # 持仓数据
    assets: "assets.json"  # 资产数据
    orders: "orders.json"  # 订单数据
    executions: "executions.json"  # 成交记录
    strategies: "strategies.json"  # 策略数据
  
  # 数据备份
  backup:
    enabled: true  # 是否启用备份
    interval: 3600  # 备份间隔（秒）
    keep_days: 7  # 保留天数
    dir: "data/backup"  # 备份目录

# 缓存配置
cache:
  quote_ttl: 1  # 行情数据缓存时间（秒）
  strategy_ttl: 30  # 策略数据缓存时间（秒）
  position_ttl: 60  # 持仓数据缓存时间（秒）
  order_ttl: 10  # 订单数据缓存时间（秒）

# 监控配置
monitor:
  check_interval: 30  # 策略检查间隔（秒）
  health_check_interval: 300  # 健康检查间隔（秒）
  max_retry_count: 3  # 最大重试次数
  retry_interval: 5  # 重试间隔（秒）
  api_unavailable_threshold: 3  # API不可用阈值（次数）

# 日志配置
logging:
  level: "INFO"  # 日志级别
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"  # 日志格式
  dir: "logs"  # 日志目录
  filename: "app.log"  # 日志文件名
  max_size: 10485760  # 单个日志文件最大大小（字节）
  backup_count: 5  # 保留的日志文件数量
  console: true  # 是否输出到控制台 